# Generated by Django 5.1.2 on 2024-10-26 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=500)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Class_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Info', models.TextField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassApp.class_main')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info', models.CharField(max_length=200)),
                ('Question', models.CharField(max_length=400)),
                ('Answer', models.TextField(max_length=500)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassApp.class_section')),
            ],
        ),
        migrations.CreateModel(
            name='Class_SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Info', models.TextField()),
                ('Video', models.CharField(max_length=100)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassApp.class_section')),
            ],
        ),
    ]
