# Generated by Django 5.1.2 on 2024-10-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_question',
            name='Order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class_section',
            name='Order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class_subsection',
            name='Order',
            field=models.IntegerField(default=0),
        ),
    ]
