# Generated by Django 5.1.2 on 2024-10-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0002_class_question_order_class_section_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_question',
            old_name='Info',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='class_question',
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='class_question',
            name='Question',
        ),
        migrations.CreateModel(
            name='Class_SubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ask', models.CharField(max_length=400)),
                ('Answer', models.TextField(max_length=500)),
                ('Type', models.CharField(max_length=200)),
                ('Order', models.IntegerField(default=0)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassApp.class_question')),
            ],
        ),
    ]
